import Head from "next/head";
import Image from "next/legacy/image";
import axios from "axios";
import {  useState } from "react"; 
import { BsSearch } from "react-icons/bs";
import Weather from '../Components/Weather';

export default function Home() {
  const [city, setCity] = useState("");
  const [weatherData, setWeather] = useState({});
  const [loading, setLoading] = useState(false);
  const API_KEY = "71fd5092846ac891fa9bd2f7903eb03a";
  // const URL = `https://api.openweathermap.org/data/2.5/weather?q=India&appid=71fd5092846ac891fa9bd2f7903eb03a`;
  
  async function fetchWeather  ()  {
    setLoading(true);
   try{
    const ServerResponse = await fetch(
       "https://api.openweathermap.org/data/2.5/weather?" + 
       "q=" + 
       city + 
       "&appid=" + 
       API_KEY + 
       "&units=imperial"
       )
       console.log("City=>",city);
       console.log("API=>",API_KEY);
       const data = await ServerResponse.json();
       console.log(data);
       if(data?.cod === '400') throw data;  
       setWeather(data);
   }catch(err){
    // console.log("Error=>",err);
   }
    setCity("");
    setLoading(false);
  };


    return (
      <>
        <Head>
          <title>Weather Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]" />
        <Image
          src="https://images.unsplash.com/photo-1562494400-5b335a653209?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=462&q=80"
          layout="fill"
          className="object-cover"
        />
        <div className="relative  justify-between items-center max-w-[500px] w-full m-auto pt-4 text-white z-10  ">
          <form 
          onSubmit={fetchWeather}
          className="flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl ">
            <div>
              <input
              onChange={(e)=>setCity(e.target.value)}
              className="bg-transparent border-none text-white focus:outline-none text-2xl " type="text" placeholder="search city" />
            </div>
            <button onClick={fetchWeather}>
              <BsSearch size={20} />
            </button>
          </form>
          {Object.keys(weatherData).length!==0 ? 
          <>
         <Weather data = {weatherData} />
          </>
          : null
          }
        </div>
      </>
    );
  
}
